### ISSUE TITLE
peer to peer code review

### ISSUE THREAD

**Issue by binhussen** [Elijahdre/To-do-List#4]
### Acknowledgment
- We appreciate the way you Completed your task, it is clean, clear and implemented principles 
### Improvement 
   Kindly fix the bellow issues
- your delete icon is omitted try to make it appear 
- remove unnecessary html tags
- fix padding issues on list of tasks when it clicked
- add MIT license in your readme file

**Comment by Elijahdre** [comment]
Hi @binhussen Thank you guys for this review. Fixed
